### ISSUE TITLE
Toggle menu doesn't appears

### ISSUE THREAD

**Issue by scramatte** [dcasia/column-toggler#11]
Hi,

I've just installed your component but  toggle menu doesn't appears on the index view
Any idea of what occurs?

I've got similar issue with your expandable row component

Regards

**Comment by milewski** [comment]
It is mostly likely you are using another package that overrides native nova components instead of extending it, can you post your composer json so I can point out which package is the offending one.

**Comment by scramatte** [comment]
Hi, 

Thank you to reply. 

I've been able  to get working column toggler. 
It's looks that the problem was with [datomatic/nova-detached-actions](https://github.com/datomatic/nova-detached-actions) package.

I've removed it as you have got some similar package to achieve same job.

**Comment by milewski** [comment]
Okay, it's unfortunate that many packages out there completely replaces the nova components.. There is a way to extend but maybe people are just not very good at vue

**Comment by majdcodes** [comment]
@milewski can you please share this way? thanks

**Comment by milewski** [comment]
Take a look at how I implemented it in this package: https://github.com/dcasia/column-toggler/blob/2e4e3e0720083e9fdf3c62b45259f63d00807dcd/resources/js/tool.js#L54-L59

Instead of completely overriding the toolbar, I wait for it to be mounted, and then manually render a new vnode exactly where I want. This way, I dont have to override the original toolbar, and any changes the Nova team makes to it won't affect this package.
