### ISSUE TITLE
Package is in conflict with shuvroroy/nova-dynamic-views

### ISSUE THREAD

**Issue by webard** [dcasia/column-toggler#26]
Hello,

after installing `shuvroroy/nova-dynamic-views` package, Column Toggler stop works on Lenses. On Resources everything is fine. I didn't dig deeper, probably `nova-dynamic-views` package hooks to the same component (lens-header?) as this package. The mystery is why this package works correctly on resources.

**Comment by milewski** [comment]
The reason is because that package overrides a lot of native nova components instead of extending it.. If you look here this line is the problem https://github.com/shuvroroy/nova-dynamic-views/blob/8d524de9590d3d457289b50a4a10715901ea24ad/resources/js/tool.js#L19

It is tonally possible to extend the functionality of the existing component without overriding it, look what this package is doing and you will be able to see how the extentions are done..

**Comment by HugoHeneault** [comment]
Hi there!

Thanks for the tip that helped point that https://github.com/datomatic/nova-detached-actions/issues/5 was conflicting (had to remove all our packages and reinstall them one by one 😅)

Great package, thanks for your work!
